### ISSUE TITLE
Angular material compatibility

### ISSUE THREAD

**Issue by hack2024** [serhiisol/ngx-auth#51] opened 2019-09-11 18:54 UTC
Hi! i am updating my Angular aplication from 7 to 8 and when i update angular material with **ng update @angular/material** i see the next warnings:

Package "ngx-auth" has an incompatible peer dependency to "@angular/compiler" (requires ">=7.0.0",
 would install "9.0.0-next.5").

please help.

**Comment by serhiisol** [comment] 2019-09-11 18:58
Hi @hack2024. Interesting, `>=` means pretty much everything above version `7.0.0` I have no idea why that doesn't work for you. We can't try bumping versions, but I'm not really sure if that will help and won't break any other packages that are dependent on this one.

**Comment by hack2024** [comment] 2019-09-11 18:58
this is the complete output

Package "ngx-auth" has an incompatible peer dependency to "@angular/core" (requires ">=7.0.0", wou
ld install "9.0.0-next.5").
                  Package "ngx-auth" has an incompatible peer dependency to "@angular/common" (requires ">=7.0.0", w
ould install "9.0.0-next.5").
                  Package "ngx-auth" has an incompatible peer dependency to "@angular/router" (requires ">=7.0.0", w
ould install "9.0.0-next.5").
                  Package "ngx-auth" has an incompatible peer dependency to "@angular/compiler" (requires ">=7.0.0",
 would install "9.0.0-next.5").

**Comment by serhiisol** [comment] 2019-09-11 18:59
what's the npm/yarn version?

**Comment by hack2024** [comment] 2019-09-11 19:06
ng --version output


Angular CLI: 8.3.3
Node: 10.16.3
Npm: 6.9.0
OS: darwin x64
Angular: 8.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.803.3
@angular-devkit/build-angular      0.803.3
@angular-devkit/build-optimizer    0.803.3
@angular-devkit/build-webpack      0.803.3
@angular-devkit/core               8.3.3
@angular-devkit/schematics         8.3.3
@angular/cdk                       7.3.7
@angular/cli                       8.3.3
@angular/fire                      5.2.1
@angular/material                  7.3.7
@angular/material-moment-adapter   7.3.7
@ngtools/webpack                   8.3.3
@schematics/angular                8.3.3
@schematics/update                 0.803.3
rxjs                               6.5.3
typescript                         3.5.3
webpack                            4.39.2

**Comment by serhiisol** [comment] 2019-09-20 18:36
What version of npm/yarn do you have?

**Comment by serhiisol** [comment] 2019-10-05 15:14
Could you provide more details cause I'm unable to reproduce, until then currently closing this issue

**Closed by serhiisol** 2019-10-05 15:14 UTC
