### ISSUE TITLE
Whitelist/Blacklist URL

### ISSUE THREAD

**Issue by mm185** [serhiisol/ngx-auth#40] opened 2019-01-19 01:27 UTC
Hey first, really cool project! 
Is there a possibility to whitelist/blacklist urls for the access token?
As an example I only want to send the access token to my internal api.
So I would like to add the url to some kind of whitelist.

**Comment by megaterrarc** [comment] 2019-01-20 16:16
try https://github.com/serhiisol/ngx-auth-example/blob/master/src/app/shared/authentication/authentication.service.ts

/**
   * Verify that outgoing request is refresh-token,
   * so interceptor won't intercept this request
   * @param {string} url
   * @returns {boolean}
   */
  public verifyTokenRequest(url: string): boolean {
    return url.endsWith('/refresh');
  }

**Comment by serhiisol** [comment] 2019-01-20 16:18
By default, library will tokens to all requests, technically yes, you can use method `verifyTokenRequest` to mark request as refresh, so it won't add token to it, but I was thinking to add this feature in the #38.

**Comment by mm185** [comment] 2019-01-20 21:42
Thanks `verifyTokenRequest` works great for blacklisting, so it won't send the token to special urls. Whitelisting (e.g. internal api) would be even better. Eliminates the risk that we forget to add urls to blacklist.

**Comment by serhiisol** [comment] 2019-09-11 18:59
I'm going to add this asap :)

**Comment by serhiisol** [comment] 2019-09-11 19:00
dupe of #38

**Closed by serhiisol** 2019-09-11 19:00 UTC
